## Fancy Indexing vs np.Where() 

In [6]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5])
indices = [0, 1, 2]
print(numbers[indices])


[1 2 3]


In [7]:
# where is exactly as masking in numpy
where_result = np.where(numbers > 3)
print(where_result)
print("NP Where", numbers[where_result])

(array([3, 4]),)
NP Where [4 5]


## Adding and Removing Data 

In [8]:
arr1 = np.array ([1, 2, 3, 4, 5])
arr2 = np.array ([6, 7, 8, 9, 10])
print(np.concatenate([arr1, arr2])) # Combine two arrays
print(np.vstack([arr1, arr2])) # Stack vertically
print(np.hstack([arr1, arr2])) # Stack horizontally

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


## Array Compatibility 
Shape compatibile hai ki nai. 
Dimension jaan sakte hai 


In [9]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
c = np.array([11, 12, 13, 14, 15, 16])
print ("Compatbility Shapes", a.shape == b.shape)
print ("Compatbility Shapes", a.shape == c.shape)

Compatbility Shapes True
Compatbility Shapes False
