## Fancy Indexing vs np.Where() 

In [6]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5])
indices = [0, 1, 2]
print(numbers[indices])


[1 2 3]


In [7]:
# where is exactly as masking in numpy
where_result = np.where(numbers > 3)
print(where_result)
print("NP Where", numbers[where_result])

(array([3, 4]),)
NP Where [4 5]


## Adding and Removing Data 

In [ ]:
arr1 = np.array ([1, 2, 3, 4, 5])
arr2 = np.array ([6, 7, 8, 9, 10])
print(np.concatenate([arr1, arr2])) # Combine two arrays
print(np.vstack([arr1, arr2])) # Stack vertically = row
print(np.hstack([arr1, arr2])) # Stack horizontally = column 

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


## Array Compatibility 
Shape compatibile hai ki nai. 
Dimension jaan sakte hai 


In [9]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
c = np.array([11, 12, 13, 14, 15, 16])
print ("Compatbility Shapes", a.shape == b.shape)
print ("Compatbility Shapes", a.shape == c.shape)

Compatbility Shapes True
Compatbility Shapes False


## Extra Operations

In [15]:
original = np.array([[1, 2] [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack([original, new_row])
print(original)
print(with_new_row)




<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/var/folders/t4/828xv04d2psdbjcdfny0c79m0000gn/T/ipykernel_89019/3795490539.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  original = np.array([[1, 2] [3, 4]])


TypeError: list indices must be integers or slices, not tuple

## Deletion

In [16]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 1)
print(deleted)

[1 3 4 5]
