## Numpy Arrays and Basics
NumPy arrays are the core data structure in NumPy. They are similar to Python lists. 
NumPy is a powerful Python library used for numerical computing.
It provides support for large, multi-dimensional arrays and matrices
Its a collection of mathematical functions to operate on these arrays efficiently.

In [2]:
import numpy as np
# Creating a 1D NumPy array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# CREATING 2D NUMPY ARRAY
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
# np.zeros(shape): Creates an array filled with zeros.
#CREATING ARRAYS WITH ZEROES
zeros_array = np.zeros((3, 3))  # 3x3 array filled with zeros
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# np.ones(shape): Creates an array filled with ones.
#CREATING ARRAYS WITH ONES
ones_array = np.ones((3, 3))  # 3x3 array filled with ones
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#CREATING ARRAYS WITH A RANGE OF NUMBERS
range_array = np.arange(1, 10)  # Array with numbers from 1 to 9
print(range_array)

[1 2 3 4 5 6 7 8 9]


In [7]:
#CREATING ARRAYS WITH RANDOM NUMBERS
random_array = np.random.rand(3, 3)  # 3x3 matrix with random values
print(random_array)

[[0.83160511 0.94790531 0.91834932]
 [0.55451036 0.9950654  0.96452652]
 [0.71063799 0.63527442 0.12143048]]


In [8]:
# np.empty(shape): Creates an uninitialized array (contains garbage values).
#CREATING AN EMPTY ARRAY
empty_array = np.empty((3, 3))
print(empty_array)

[[0.83160511 0.94790531 0.91834932]
 [0.55451036 0.9950654  0.96452652]
 [0.71063799 0.63527442 0.12143048]]


In [9]:
# Full array - sab mein constant milega 
full_array = np.full((3, 3), 5)  # 3x3 array filled with 5s
print(full_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
