# List vs Numpy array 

In [1]:
import numpy as np
py_list = [1,2,3]
print("Python list multiplication", py_list * 2)  # Here 2 is scaler quantity.

np_array = np.array([1,2,3])
print("Numpy array multiplication", np_array * 2)  # Here 2 is scaler quantity.

Python list multiplication [1, 2, 3, 1, 2, 3]
Numpy array multiplication [2 4 6]


In [2]:
import time 
start = time.time()
py_list = [i for i in range(1000000)]
py_list = [i*2 for i in py_list]
print("Python list time", time.time() - start)

start = time.time()
np_array = np.arange(1000000)
np_array = np_array * 2
print("Numpy array time", time.time() - start)

Python list time 0.06275701522827148
Numpy array time 0.002295970916748047


## Vector, Matrix and Tensor 


In [4]:
vector = np.array([1,2,3])
print("Vector", vector)

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Matrix", matrix)

tensor = np.array ([[[1,2], [3,4], 
                     [5,6]], [[7,8], 
                    [9,10], [11,12]]])
print("Tensor", tensor)
                    

Vector [1 2 3]
Matrix [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
