## Arrays Properties

In [1]:
import numpy as np

arr = np.array ([[1,2,3],
                 [4,5,6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)        #ndim - number of dimensions
print("Data type", arr.dtype)       #dtype - data type
print("Size", arr.size)             #size - number of elements

Shape (2, 3)
Dimension 2
Data type int64
Size 6


## Array Reshaping 

In [ ]:
arr = np.arange (12)
print("Original array", arr)

reshaped_arr = arr.reshape(3,4)
print("Reshaped array", reshaped_arr)

flatten_arr = reshaped_arr.flatten()
print("Flattened array", flatten_arr)

# ravel() function is similar to flatten() function
# returns view instead of copy
ravel_arr = reshaped_arr.ravel()
print("Raveled array", ravel_arr)

transpose_arr = reshaped_arr.T     #T - transpose - swaps the rows and columns of the array. 
print("Transposed array", transpose_arr)


Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
